== Use Cases

The following are the typical use cases for our platform:

=== An Administrator Hosts a Market Place

A wise yet simple minded individual (e.g. he uses Linux you see), 
wants to install and maintain (host) an instance of the KipOpen 
marketplace application in his computer so that he can make a hefty 
return while others can exchange designs and products on it.

He proceeds to download the platform and install it in his 
computer, then he follows all of the easy steps to host a site 
(domain registration, allocation of a static IP, getting SSL 
certificate ...etc) and contacts his local network of rich 
friends/acquaintances which start using the platform at once. Soon 
money starts rolling in (gonna need a couple of sacks). 

=== A Developer Creates a Project

A bright unemployed engineer (he is a bit cocky and has poor 
communication skills) comes with an idea to the marketplace, he 
would like to create a project to receive funding and work full 
time on his open idea while making a decent seven-figures income. 

An electrical engineer creates a project, follows the guidelines in 
the platform (builds his requirements, design and financial plan) 
and recruits a design team. Then he opens his project for 
investment and negotiates with potential investors to reach an 
agreement. Development starts and scheduled milestones are met, 
finally he completes the project, releases the design and 
delivers the return to all applicable investors (depending on their 
percent of ownership on the project).

=== A Developer Joins a Project

A recent grad computer scientist is browsing through the platform 
to find a meaningful open project to work on (she quit her last job 
at the book-face.com; too many ads), she would like to join the 
design team of a project, work full time and earn a living.

An ad-blocker project is currently seeking technical team 
members. She expresses interest and the creator of the project 
interviews her, they negotiate potential salary conditions if 
successfully funded. The programmer is added to the project's 
design team, the project is capitalized and the programmer starts 
working on the product.
    
=== An Individual Investor Funds a Project

An _informed_ consumer (again note the use of the word 
''informed'', not _marketing-prey_ or _tv-misinformed_) is browsing 
through the platform, he finds an open design which fulfills his 
needs. He would like to purchase shares to support the project, 
vote on proposals and use the software application.

A well-meaning design team is currently seeking to develop an open 
tax platform (tus-botas) to help people understand and fill their 
taxes independently. An individual investor is very 
interested on the program, he looks over the user and technical 
details and purchases a single voting share on the project 
(e.g. worth $10). Then he launches a board proposal to add 
support for the form W-2 for his small company (very sneaky), 
the proposal receives the support of the other shareholders and 
is added to the requested features, a new project price is quoted 
for the added effort and investors vote to accept the proposal, 
the project is developed and the investors receive their tax 
preparation software (along with a new pair of boots).

=== An Institutional Investor Funds a Project

A money-driven nice-looking engineering manager is browsing through 
the platform and finds an interesting project that could be 
integrated to his software application and meet a required feature 
at a fraction of the cost (outsourcing means bigger bonuses you 
know). 

A manager from Soft & Micro Inc sees an interesting project that 
could come in very useful as a hand-writing recognition add-on to 
his ''little'' note-taking company software (2-note). He purchases 
the majority of the shares on the project and votes on multiple 
proposals to tailor the project to fit his company needs, then he 
negotiates with the design team and they reach an agreement. The 
project is completed, released and the engineering manager receives 
his return and integrates the open functionality to his note-taking 
software, he receives a bonus and spends it on a new electric car. 

=== An Investor Creates a Project

An informed consumer (either an individual investor or an 
institutional investor) creates a project with specific user 
requirements. A technical team takes-on the project, receives 
funding and releases the application. 

An informed consumer has an idea for the development of a 
fingerprint lock (yes, another smart lock, because taking the keys 
out of your pocket is unnecessary, _just imagine how much time you 
could save_). He generates a set of desired user requirements and 
updates the status of the project to ''seeking smart developers''. 
An interested design team takes-on the project and continues 
building the campaign. The project receives funding and the 
fingerprint lock design is released for production.

