= User Functional Specification
Camilo Tejeiro  <camilo.tejeiro@gmail.com>
:Date:          {docdate}
:Revision:      0.1
:toc:
:sectnums:

NOTE: Bear in mind, this document is incomplete;
a really rough draft that we will use as our starting point. As we move
forward, this document will take shape and assume a more polished look.

NOTE: When we refer to "open technology", we don't mean a specific
movement/license in general (e.g. libre software vs open source ...etc).
There are pros and cons to each open/libre license and our platform
supports all major ones, ultimately this is something that developers
should discuss with their investors.

IMPORTANT: This document *must not* be dry and boring.
Keep this document entertaining (e.g. use humor) so that
people actually want to read it and it gets maintained, otherwise this
document will be useless.

// Introduction
include::introduction.adoc[]

// Project Overview
include::project_overview.adoc[]

// User Characteristics
include::user_characteristics.adoc[]

// Operational Environment
include::operational_environment.adoc[]

// Use Cases
include::use_cases.adoc[]

// Postponed/Removed Features
include::postponed_removed_features.adoc[]

// Visual Specification
include::visual_spec.adoc[]
