:wireframes: ../wireframes
:login_page_wireframe: {wireframes}/login_page/login_page_wireframe_desktop.svg


=== Login/Registration Page

The Login page can be accessed directly through the browser url
(e.g. marketplace.com/login register), or from the navigation bar at
the top of any page. The login/registration page allows people to
register for an account if they don’t have one or login into their
existent account (this is pretty self-explanatory right?).

==== Wireframe

image::{login_page_wireframe}[Login Page Wireframe]

For mobile devices:: The layout for the mobile device login page is
simply the inner login window inside the desktop layout (see desktop
wireframe below).

==== Actionable Items

The login page has the following page specific items:

[qanda]
*LOGIN("Login Button")*::
    Used to confirm the user credentials and redirect users to the _User
    Account page._

*Stay Signed In ("Stay signed in Check-box")*::
    Used to save the user session upon login.

*Forgot your password("Forgot your password Link")*::
    Used to direct the user to the _Password Recovery_ page.

*Register here ("Register here Link")*::
    Used to direct the user to the _User Registration_ page.
