== Competitive Advantage

To guarantee the adoption of open technologies at a wide scale,
we need to make sure we have better economic incentives for both
the users as well as for the developers of open technology. In other
words, we need to establish a clear competitive advantage over
closed proprietary technology, ultimately if we want adoption
*We must compete* for market share.

The following economic incentives are in place for every type of user:

KipOpen Site Administrators::
    Receive a commission for every project funded on their crowdfunding
    site (this is pretty standard). This is the incentive they have to
    actually install the web application and host the site in their
    computer (most likely a small single board computer).

KipOpen Consumers (aka Investors)::
    Trade directly with developers and can purchase shares on the project
    to receive return incentives for a fraction of the cost (i.e. there
    is no corporate, marketing or other unnecessary business overhead).
    Example return incentives include (these will differ depending on
    the technology sector): Hardware units, project voting rights
    (e.g. the right to vote on new features), support packages... etc.
    Consumers are incentivized to invest in open technology because
    they get better value.

KipOpen Developers::
    Trade directly with consumers and can now earn money from
    developing open applications. This means that current open
    technology developers now have a choice of working on open designs
    on a full-time basis, furthermore it also means that entrepreneurs
    can start their own company to design complete open products funded
    through different KipOpen crowdfunding sites (specializing in different
    stages of development).
